services:
  - type: web
    name: insight-logger
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_SHEET_WEBHOOK
        sync: false
